import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Post from "~/components/Post";

interface IPosts {
  usuario: string;
  conteudo: string;
}

const fetchPosts = async () => {
  const result = await fetch("http://localhost:3000");

  const res = result.json();

  return res as Promise<IPosts[]>;
};

const Home: NextPage = () => {
  const [posts, setPosts] = useState<IPosts[]>([] as IPosts[]);

  useEffect(() => {
    let ignore = false;

    void fetchPosts().then((r) => {
      if (!ignore) {
        setPosts(r);
      }
    });
    return () => {
      ignore = false;
    };
  }, []);

  return (
    <>
      <Head>
        <title>Postagens</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto h-screen w-screen bg-slate-700 p-6">
        <h1 className="text-center text-5xl text-slate-200">Posts de hoje!</h1>
        <div className="mx-auto flex flex-col justify-center space-y-3 px-12 pt-6">
          {posts.map((p, index) => {
            return (
              <Post username={p.usuario} key={index}>
                {p.conteudo}
              </Post>
            );
          })}
        </div>
      </div>
    </>
  );
};

export default Home;
